# Generated by Django 2.1.4 on 2018-12-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('time', models.DateField(blank=True, max_length=100, null=True, verbose_name='发表时间')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='内容')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='文章类型')),
            ],
        ),
    ]
