# Generated by Django 2.1.4 on 2018-12-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181207_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, height_field='url_height', null=True, upload_to='icons', verbose_name='图片', width_field='url_width'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='摘要'),
        ),
    ]
