# Generated by Django 2.1.4 on 2018-12-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181228_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='图片'),
        ),
    ]
