# Generated by Django 2.1.4 on 2018-12-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181228_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='摘要'),
        ),
    ]
